//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Data.Mach1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contact()
        {
            this.Contact1 = new HashSet<Contact>();
            this.ContactAddressRelationships = new HashSet<ContactAddressRelationship>();
        }
    
        public int ContactID { get; set; }
        public string ContactType { get; set; }
        public string NTLogin { get; set; }
        public string MarketingType { get; set; }
        public bool IsParent { get; set; }
        public Nullable<int> AccountManagerID { get; set; }
        public string TaxScheduleID { get; set; }
        public string ScheduleSerialNums { get; set; }
        public Nullable<decimal> BlanketAmt { get; set; }
        public Nullable<System.DateTime> InsuranceExpirationDate { get; set; }
        public string InsuranceType { get; set; }
        public Nullable<System.DateTime> CreditLastReviewDate { get; set; }
        public Nullable<decimal> CreditLimitAmt { get; set; }
        public string CreditDesignation { get; set; }
        public string SubsidiaryType { get; set; }
        public string CompanyName { get; set; }
        public string FullLegalName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string JobTitle { get; set; }
        public string QuickNote { get; set; }
        public string Suffix { get; set; }
        public string FileAs { get; set; }
        public string PrimaryPhone { get; set; }
        public string PrimaryPhoneExt { get; set; }
        public string HomePhone { get; set; }
        public string HomeFax { get; set; }
        public string MobilePhone { get; set; }
        public string AssistantName { get; set; }
        public string AssistantEmail { get; set; }
        public string AssistantPhone { get; set; }
        public string AssistantPhoneExt { get; set; }
        public string AssistantFax { get; set; }
        public string BusinessPhoneCountry { get; set; }
        public string BusinessPhone { get; set; }
        public string BusinessPhoneExt { get; set; }
        public string BusinessPhone2 { get; set; }
        public string BusinessPhone2Ext { get; set; }
        public string CompanyMainPhone { get; set; }
        public bool IntlPhoneFormat { get; set; }
        public string Email { get; set; }
        public string Email2 { get; set; }
        public string Pager { get; set; }
        public string BusinessFax { get; set; }
        public bool Active { get; set; }
        public string OtherPhone { get; set; }
        public string OtherFax { get; set; }
        public bool Deletable { get; set; }
        public bool NoSpamEmail { get; set; }
        public string URL { get; set; }
        public string GpClass { get; set; }
        public bool EmailList { get; set; }
        public Nullable<int> ContactPictureFileID { get; set; }
        public string Source { get; set; }
        public Nullable<System.DateTime> DateVerified { get; set; }
        public string EnterUserStr { get; set; }
        public System.DateTime EnterDateTime { get; set; }
        public string EditUserStr { get; set; }
        public System.DateTime EditDateTime { get; set; }
        public byte[] TimeStamp { get; set; }
        public string Endorsements { get; set; }
        public string CreditNotes { get; set; }
        public string InsuranceContact { get; set; }
        public string RUCDNI { get; set; }
        public string FileNumber { get; set; }
        public string Jurisdiction { get; set; }
        public bool WarnIfTaxable { get; set; }
        public bool InvoicesRequirePO { get; set; }
        public string EmailInvoicesTo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact> Contact1 { get; set; }
        public virtual Contact Contact2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactAddressRelationship> ContactAddressRelationships { get; set; }
        public virtual ActiveForSaleContact ActiveForSaleContacts { get; set; }
    }
}
