//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Data.Mach1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactAddressRelationship
    {
        public int ContactAddressRelationshipID { get; set; }
        public int ContactID { get; set; }
        public int AddressID { get; set; }
        public bool Active { get; set; }
        public string EnterUserStr { get; set; }
        public System.DateTime EnterDateTime { get; set; }
        public string EditUserStr { get; set; }
        public System.DateTime EditDateTime { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Contact Contact { get; set; }
    }
}
